server:
  port: 9001

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/your_database?useSSL=false&serverTimezone=UTC

mybatis:
  type-aliases-package: com.lynz.logisticsmanagementsystem.pojo
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      example:
        mapper: debug
